<a href="https://colab.research.google.com/github/spandana9318/Scikit_learn/blob/main/AdaBoost_for_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [2]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
df = pd.concat([train, test], sort = False)

In [4]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [5]:
import numpy as np
import seaborn as sns

In [6]:
import matplotlib.pyplot as plt

In [8]:
df.isnull().sum()

PassengerId       0
Survived        418
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [10]:
df = df.drop('Cabin', axis=1)

In [11]:
from sklearn.impute import SimpleImputer
print(f"Number of null values in Age column before impotation: {df.Age.isnull().sum()}")
si = SimpleImputer(strategy='mean')
df['Age'] = si.fit_transform(df[['Age']])
print(f"Number of null values in Age column after impotation: {df.Age.isnull().sum()}")

Number of null values in Age column before impotation: 263
Number of null values in Age column after impotation: 0

In [14]:
df['Survived'] = si.fit_transform(df[['Survived']])
print(f"Number of null values in Survived column after impotation: {df.Survived.isnull().sum()}")

Number of null values in Survived column after impotation: 0

In [18]:
si1 = SimpleImputer(strategy = 'most_frequent')
df['Embarked'] = si1.fit(df[['Embarked']])

In [19]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [20]:
df['Fare'] = si1.fit_transform(df[['Fare']])

In [21]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [22]:
df = df.drop(['Name','Ticket'], axis=1)

In [23]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.000000,3,male,22.000000,1,0,7.2500,SimpleImputer(strategy='most_frequent')
1,2,1.000000,1,female,38.000000,1,0,71.2833,SimpleImputer(strategy='most_frequent')
2,3,1.000000,3,female,26.000000,0,0,7.9250,SimpleImputer(strategy='most_frequent')
3,4,1.000000,1,female,35.000000,1,0,53.1000,SimpleImputer(strategy='most_frequent')
4,5,0.000000,3,male,35.000000,0,0,8.0500,SimpleImputer(strategy='most_frequent')
...,...,...,...,...,...,...,...,...,...
413,1305,0.383838,3,male,29.881138,0,0,8.0500,SimpleImputer(strategy='most_frequent')
414,1306,0.383838,1,female,39.000000,0,0,108.9000,SimpleImputer(strategy='most_frequent')
415,1307,0.383838,3,male,38.500000,0,0,7.2500,SimpleImputer(strategy='most_frequent')
416,1308,0.383838,3,male,29.881138,0,0,8.0500,SimpleImputer(strategy='most_frequent')
417,1309,0.383838,3,male,29.881138,1,1,22.3583,SimpleImputer(strategy='most_frequent')

In [28]:
threshold = 3
from scipy.stats import zscore
numerical_features = ['Fare', 'Age']
z_scores=np.abs(zscore(df[numerical_features]))
print(z_scores)

[[0.85019689 0.96184978]
 [1.86868613 1.0871246 ]
 [0.84052197 0.44960618]
 ...
 [0.85019689 1.15115505]
 [0.83361132 0.0474158 ]
 [0.04257377 0.0474158 ]]

In [29]:
outliers = np.where(z_scores > threshold)
print(outliers)

(array([], dtype=int64), array([], dtype=int64))

In [30]:
from scipy.stats.mstats import winsorize

df['Age'] = winsorize(df['Age'], limits = [0.15, 0.15])
df['Fare'] = winsorize(df['Fare'], limits = [0.15, 0.15])

In [31]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()
df['Sex'] = oe.fit_transform(df[['Sex']])

In [32]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.000000,3,1.0,22.000000,1,0,7.7500,SimpleImputer(strategy='most_frequent')
1,2,1.000000,1,0.0,38.000000,1,0,56.9292,SimpleImputer(strategy='most_frequent')
2,3,1.000000,3,0.0,26.000000,0,0,7.9250,SimpleImputer(strategy='most_frequent')
3,4,1.000000,1,0.0,35.000000,1,0,53.1000,SimpleImputer(strategy='most_frequent')
4,5,0.000000,3,1.0,35.000000,0,0,8.0500,SimpleImputer(strategy='most_frequent')
...,...,...,...,...,...,...,...,...,...
413,1305,0.383838,3,1.0,29.881138,0,0,8.0500,SimpleImputer(strategy='most_frequent')
414,1306,0.383838,1,0.0,39.000000,0,0,56.9292,SimpleImputer(strategy='most_frequent')
415,1307,0.383838,3,1.0,38.500000,0,0,7.7500,SimpleImputer(strategy='most_frequent')
416,1308,0.383838,3,1.0,29.881138,0,0,8.0500,SimpleImputer(strategy='most_frequent')
417,1309,0.383838,3,1.0,29.881138,1,1,22.3583,SimpleImputer(strategy='most_frequent')

In [33]:
df['Embarked'] = oe.fit_transform(df[['Embarked']])

In [34]:
df['Survided'] = oe.fit_transform(df[['Survived']])

In [35]:
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Survided
0,1,0.000000,3,1.0,22.000000,1,0,7.7500,0.0,0.0
1,2,1.000000,1,0.0,38.000000,1,0,56.9292,0.0,2.0
2,3,1.000000,3,0.0,26.000000,0,0,7.9250,0.0,2.0
3,4,1.000000,1,0.0,35.000000,1,0,53.1000,0.0,2.0
4,5,0.000000,3,1.0,35.000000,0,0,8.0500,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
413,1305,0.383838,3,1.0,29.881138,0,0,8.0500,0.0,1.0
414,1306,0.383838,1,0.0,39.000000,0,0,56.9292,0.0,1.0
415,1307,0.383838,3,1.0,38.500000,0,0,7.7500,0.0,1.0
416,1308,0.383838,3,1.0,29.881138,0,0,8.0500,0.0,1.0
417,1309,0.383838,3,1.0,29.881138,1,1,22.3583,0.0,1.0

In [48]:
X = df.drop('Survived', axis=1)
y = df['Survived']

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size = 0.30, random_state = 0)

In [52]:
from sklearn.ensemble import AdaBoostClassifier
ab = AdaBoostClassifier(n_estimators = 100,learning_rate = 1, random_state = 0)
ab.fit(X_train, y_train)
y_pred = ab.predict(X_test)

In [53]:
df['Survived'].dtype
df['Survived'].value_counts()

Survived
0    967
1    342
Name: count, dtype: int64

In [54]:
df['Survived'] = df['Survived'].astype(int)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred, y_test)

1.0